### ISSUE TITLE
Auto Enable Audio to Haptics

### ISSUE THREAD

**Issue by Rivridis** [WujekFoliarz/DualSenseY-v2#10]
Amazing work, this is much better than DSX. Is there any way to auto enable audio to haptics when app is opened, instead of manually clicking the start button?

**Comment by WujekFoliarz** [comment]
I'll try to add that

**Comment by Rivridis** [comment]
Thanks a lot!

**Comment by WujekFoliarz** [comment]
1. Check "Run audio to haptics on start" in Haptic Feedback tab
2. Save config in Config tab
3. Set default config for this port in Config tab and open the config you've saved

Now Audio To Haptics window should open by itself on that specific USB port

**Comment by Rivridis** [comment]
Yup, works perfectly. Just a small nitpick, but the haptics audio popup is not auto minimizing when Hide to Tray is on. Not a big deal though, so closing the issue. Thanks for the hard work.
