### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by techjunky90** [WujekFoliarz/DualSenseY-v2#2]
Still has a memory leak.

**Comment by WujekFoliarz** [comment]
Just by running the app or durning emulation?

**Comment by WujekFoliarz** [comment]
I'm having a hard time to make it happen on my PC

**Comment by WujekFoliarz** [comment]
I'm having a hard time to make it happen on my PC

**Comment by WujekFoliarz** [comment]
Okey I think I got something on this problem, update soon

**Comment by WujekFoliarz** [comment]
Try the new version
