### ISSUE TITLE
The application does not start

### ISSUE THREAD

**Issue by shosh1337** [WujekFoliarz/DualSenseY-v2#7]
When I launch DSX.exe it just pops up console window for a sec and then nothing happen.
Windows 11 24h2

**Comment by WujekFoliarz** [comment]
Try version 19

**Comment by WujekFoliarz** [comment]
Also check if there is any crash logs

**Comment by shosh1337** [comment]
With 24 version program start working. Thank you!

**Comment by shosh1337** [comment]
All ok

**Comment by WujekFoliarz** [comment]
Good
