### ISSUE TITLE
DualSense not working in RDR 2

### ISSUE THREAD

**Issue by GitBoy31** [WujekFoliarz/DualSenseY-v2#8]
Hello,

I cannot figure out how to get the DualSense controller working with Red Dead Redemption 2.

I have the ViGEm Bus driver installed and have tried both 360 and DS4 emulation running as administrator with no success. The game just refuses to acknowledge the controller.

I don’t have HidHide installed because the game doesn’t even support the DualSense to begin with so it shouldn’t be necessary, right?

Also, I can confirm that DualSenseY does recognize my DualSense and that the TouchPad emulation is working fine in the software.

Any ideas?

**Comment by WujekFoliarz** [comment]
1. What version are you using
2. Check here https://hardwaretester.com/gamepad

**Comment by WujekFoliarz** [comment]
Try version 24 please
