### ISSUE TITLE
RacingDSX compatibility

### ISSUE THREAD

**Issue by eapiova** [WujekFoliarz/DualSenseY-v2#9]
Affter using DSY with RacingDSX without any problems, I switched over to DSY-v2. The connection works but the triggers behave in a very different way, at least for Forza Horizon 5 (too snappy). I don't think it is the intended way of working

Thank you for your hard working

**Comment by WujekFoliarz** [comment]
The triggers in old DSY were set-up incorrectly and many effects were missing. In V2 trigger effects are 1:1 like in DSX ver 1.4.9

**Comment by eapiova** [comment]
You're right I tested it with DSX 1.4.9 and the effects are indeed the same as your DSY-v2, even if in RacingDSX they said they only tested with DSX 2 and 3.1 I guess the implementation is the same. Thanks for the explanation
